Store/Components/ProductSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Repositories;
using Services.Contracts;

namespace Store.Components 
{
    public class ProductSummaryViewComponent : ViewComponent
    {
        private readonly IServiceManager _manager;

        public ProductSummaryViewComponent(IServiceManager manager)
        {
            _manager = manager;
        }

        public string Invoke()
        {
            return _manager.ProductService.GetAllProcucts(false).Count().ToString();
        }
    }
}

Store/Controllers/CategoryController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;

namespace Store.Controllers
{
    public class CategoryController : Controller
    {
        private IRepositoryManager _maneger;

        public CategoryController(IRepositoryManager maneger)
        {
            _maneger = maneger;
        }
        public IActionResult Index()
        {
            var model = _maneger.Category.FindAll(false);
            return View(model);
        }
    }
}

Store/Controllers/OrderController.cs
using Entities.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace Store.Controllers
{
    public class OrderController : Controller
    {
         private readonly IServiceManager _maager;
        private readonly Cart _cart;

        public OrderController(IServiceManager maager
            , Cart cart)
        {
            _maager = maager;
            _cart = cart;
        }

        [Authorize]
        public ViewResult Checkout()=>View(new Order());

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Checkout([FromForm]Order order)
        {
            if (_cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sory ,your cart is empty. ");
            }

            if (ModelState.IsValid)
            {
                order.Lines = _cart.Lines.ToArray();
                _maager.OrderService.SaveOrder(order);
                _cart.Clear();
                return RedirectToPage("/Complete", new {OrderId=order.OrderId});
            }

            else
            {
                return View();
            }
        }
    }
}

Store/Controllers/ProductController.cs
using Entities.Models;
using Entities.RequestParameters;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Repositories;
using Repositories.Contracts;
using Services.Contracts;
using Store.Models;

namespace Store.Controllers
{
    public class ProductController : Controller
    {
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index(ProductRequestParameters p)
        {

            var products = _manager.ProductService.GetAllProductsWitihDetails(p);
            var pagination = new Pagination()
            {
                CurrenPage = p.PageNumber,
                ItemPerPage = p.PageSize,
                TotalItmes= _manager.ProductService.GetAllProcucts(false).Count()
            };
            return View(new ProductListViewModel()
            {
                Products= products,
                Pagination = pagination
            });

        }
        public IActionResult Get([FromRoute(Name ="id")]int id)
        {
            var model = _manager.ProductService.GetOneProduct(id, false);
            ViewData["Title"] = model?.ProductName;
            return View(model);

        }
    }
}

Store/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StoreApp - @ViewData["Title"]</title>
    <link rel="stylesheet" asp-append-version="true" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" asp-append-version="true" href="~/css/site.css" />
    <link rel="stylesheet" asp-append-version="true" href="~/lib/font-awesome/css/all.css" />

</head>
<body>
    <header>
   
        <partial name="_Navbar"/>
        @RenderSection("Header",false)
       
    </header>
    <div class="container">
        <div>
            <partial name="_Notification" />
        </div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
  
    <footer>
        @RenderSection("Footer",false)
   
    </footer>
   
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    @await RenderSectionAsync("Scripts",required:false)
</body>
</html>

Store/Areas/Admin/Views/Shared/_Navbar.cshtml
<nav class="navbar border-bottom border-body navbar-expand-lg bg-body-tertiary bg-dark-subtle">
    <div class="container">
        <a class="navbar-brand" href="/">Admin</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between" id="navbarNavAltMarkup">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" asp-controller="Product" asp-action="Index">Products (@await Component.InvokeAsync("ProductSummary"))</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" asp-controller="Category" asp-action="Index">Category</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" asp-controller="Order" asp-action="Index">Orders</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" asp-controller="Role" asp-action="Index">Role</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" asp-controller="User" asp-action="Index">Users</a>
                </li>
            </ul>


            <ul class="navbar-nav">
                <li class="nav-item">
                    <a target="_blank" class="nav-link active" aria-current="page" asp-area="" asp-controller="Home" asp-action="Index">
                        <i class="fa fa-solid fa-search"></i>
                        Web</a>
                </li>

                <li class="nav-item">
                    <a  class="nav-link active" aria-current="page" asp-area="" asp-controller="Account" asp-action="Logout">
                       <i class="fa fa-solid fa-right-from-bracket"></i>
                        Logout</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

Store/Areas/Admin/Views/Shared/_OrderDetails.cshtml
@model Order
@{
    var total = Model.Lines.Sum(c => c.Product.Price * c.Quantity);
}

<div class="row shadow my-3">
    <div class="col-md-3 border-1 border-dark p-3 bg-light shadow">
        <h5 class="display-5 text-center">
            <i class="fa fa-address-book text-bg-danger"></i>
            <br />
            @Model.Name
        </h5>
        <p>@Model.Line1</p>
        <p>@Model.Line2</p>
        <p>@Model.Line3</p>
        <p>@Model.City</p>
        <p class="rounded-2 p-3">
            <span class="bg-warning p-2">Shipped</span>
            <span class="bg-info p-2">@(Model.Shipped ? "Complated":"In Progress")</span>
        </p>
    </div>
    <div class="col-md-9">
        <h6 class="display-6 mt-3 text-center">
            Cart
        </h6>
        <ul class="list-group">
            @foreach(var cartItem in Model.Lines)
            {
                <li class="list-group-item d-flex justify-content-between brand">
                    @cartItem.Product.ProductName
                    <b>@cartItem.Quantity * @cartItem.Product.Price.ToString("C2")
                        =@((cartItem.Quantity*cartItem.Product.Price).ToString("C2"))
                    </b>
                </li>
            }
            <li class="list-group-item d-flex justify-content-between text-danger">
                Total
                <b>@total.ToString("C2")</b>
            </li>
        </ul>
        <div class="text-center mt-2 p-2">
            <form method="post" asp-action="Complete">
                <input type="hidden" name="id" value="@Model.OrderId"/>
                <button type="submit" class="btn btn-primary" disabled="@Model.Shipped">
                    Complete
                    </button>
            </form>
        </div>
    </div>
</div>